### ISSUE TITLE
`throws Exception` was removed from WebSecurityConfigurerAdapter#configure(WebSecurity)

### ISSUE THREAD

**Issue by MasatoshiTada** [spring-projects/spring-security#7541]
### Summary

`throws Exception` was removed from `WebSecurityConfigurerAdapter#configure(WebSecurity)` with the commit below.

https://github.com/spring-projects/spring-security/commit/34dd5fea30d4e3d862dfc675cb97cf967a6ad25b#diff-5cc9a70efb559a4a15966c3b7215538c

When we upgrade from 5.1.x to 5.2.0.RELEASE, this occurs compilation error in subclasses of `WebSecurityConfigurerAdapter` in our application codes.

### Expected Behavior

`throws Exception` should not be removed, or it should be written in Release Notes as the incompatibility.

### Version

spring-security-config 5.2.0.RELEASE

**Comment by MasatoshiTada** [comment]
Amazing! Thank you for your quick fixing!😆
