### ISSUE TITLE
Allowing OAuth2 login does not conform to OpenID Connect Specification.

### ISSUE THREAD

**Issue by cpore** [spring-projects/spring-security#10351]
### Summary
Hi folks, can we have a discussion about the /userinfo endpoint? In short, authenticating a user via the /userinfo endpoint should not be used as a method of authentication. [The OpenID Connect specification requires all responses from the Token Endpoint to contain an ID Token](https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse):

>
> In addition to the response parameters specified by OAuth 2.0, the following parameters MUST be included in the response:
> 
> id_token
> ID Token value associated with the authenticated session. 
>

Spring Security OAuth2 Client allows authentication with only an access token which leads to misuse of OAuth2 as authentication mechanism. OpenID Connect was specifically designed to mitigate this kind of security flaw. Spring security should not promote or enable known bad security practices. Please don't let it be the case going forward. If users need this functionality, let them use the old Oauth2 client. Or maybe it's time to rethink trying to mix metaphors and make OpenID Connect its own distinct project independent of OAuth2.

The Spring Security Documentation states the the Oauth2 Login is implemented according to the OpenID Connect 1.0 specification (highlighted in red boxes):

![2021-10-06_14-40-39](https://user-images.githubusercontent.com/1735726/136280616-42671993-f8ca-4fd8-9dee-44b32d14869b.jpg)

This is demonstrably false as the OpenID Connect spec indicates the `sub` Claim in the UserInfo Endpoint Response MUST be verified against the `sub` Claim in the ID Token per [Section 5.3.2](https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse) of the spec:

> The sub (subject) Claim MUST always be returned in the UserInfo Response.
> 
> NOTE: Due to the possibility of token substitution attacks (see [Section 16.11](https://openid.net/specs/openid-connect-core-1_0.html#TokenSubstitution)), the UserInfo Response is not guaranteed to be about the End-User identified by the sub (subject) element of the ID Token. The sub Claim in the UserInfo Response MUST be verified to exactly match the sub Claim in the ID Token; if they do not match, the UserInfo Response values MUST NOT be used.

No such validation is performed on the `sub` Claim currently.

On a personal integrity note, this has caused a bit of strife in my professional life. I am part of a project that is supposed to integrate with a "new shiny authentication service", but they are using this old and insecure OAuth2 flow to exchange an Access Token for UserInfo. My team has tried to appeal to them that what they are doing is insecure, but the Spring Security project is viewed by them as an authority on the topic (which is warranted). And since you allow it, it is not even given a second thought that it may be an insecure solution to Authentication. **It's time to shut OAuth2 Authentication down.** If not, these flaws will continue to propagate in the wild.

### Actual Behavior

1. Perform Authentication flow (e.g. Authorization code flow).
2. Receive a response that contains an Access Token, but NO ID Token.
3. ID token is NOT validated or required.
4. Request for UserInfo is made to the /userinfo endpoint with Access Token obtained in step 2.
5. User is authenticated and a Principal is created without verifying the `sub` Claim in the ID Token and the `sub` Claim in the UserInfo Response match exactly.

### Expected Behavior

1. Perform Authentication flow (e.g. Authorization code flow).
2. Receive a response that contains an Access Token, but NO ID Token.
3. ID token IS validated AND required. 
4. The flow should produce an error due to missing ID Token.

Or...

1. Perform Authentication flow (e.g. Authorization code flow).
2. Receive a response that contains an Access Token and an ID Token.
3. ID token IS validated AND required. 
4. Request for UserInfo is made to the /userinfo endpoint with Access Token obtained in step 2.
5. The `sub` Claim in the UserInfo Response MUST be verified to exactly match the `sub` Claim in the ID Token.
    5a. If they do not match, the UserInfo Response values MUST NOT be used, and an error should be produced.
    5b. If they do match, you can rely on the info as supplementary user information, but should not be used as a primary authentication mechanism because that was performed in step 3.

### Configuration

See Sample

### Version

All versions affected.

### Sample

I'm only doing what is the "normal" UserInfo Authentication Flow allowed by the Oauth2 project, but this should not be allowed if trying to implement OpenID Connect. Anyhow, my code is available here:
[https://github.com/cpore/openidconnect-client-authentication](https://github.com/cpore/openidconnect-client-authentication)

**Comment by rozagerardo** [comment]
Hey @jgrandja can we revisit this issue and clarify a few points? 

I now prepared a functional sample project to point out the scenario that I believe @cpore was referring to:

https://github.com/rozagerardo/samples/tree/spring-security-with-keycloak-AS

There are three services over there to mimic a standard OAuth 2 configuration:

- A Keycloak Authorization Server
- A Spring Security OAuth 2 Client
- A Spring Security Resource Server

In the Client we **don't** use the `openid` scope, just as in the @cpore sample:

https://github.com/rozagerardo/samples/blob/spring-security-with-keycloak-AS/spring-client/src/main/resources/application.yml#L9

And we're using the `.oauth2Login(...)` setup (that is, not the `.oauth2Client()`:

https://github.com/rozagerardo/samples/blob/spring-security-with-keycloak-AS/spring-client/src/main/java/com/rozagerardosamples/spring/ClientSecurityConfig.java#L20

If you try out this configuration, you'll see that we can Log in with this setup, and that is done via the UserInfo endpoint.

Debugging the process (instructions on the README file):

1- the `OAuth2LoginAuthenticationProvider.authenticate` is invoked. This comes into play when the `openid` scope is **not** provided, as you can see here:
<img width="1263" alt="Screen Shot 2024-03-28 at 10 55 34" src="https://github.com/spring-projects/spring-security/assets/7059941/727d18c5-0773-45f3-bead-ba57017803fa">

2- This calls `DefaultOAuth2UserService.loadUser`, and we can see from starters that this uses the UserInfo endpoint to get the user data:
<img width="1263" alt="Screen Shot 2024-03-28 at 10 57 44" src="https://github.com/spring-projects/spring-security/assets/7059941/db106529-c569-4f38-bbc9-ee8b80a09889">

3- We can then later on confirm that the endpoint actually getting called for this case:
<img width="1277" alt="Screen Shot 2024-03-28 at 11 00 31" src="https://github.com/spring-projects/spring-security/assets/7059941/59d7fc03-37f6-4f41-a097-83efc9289e3d">

4- The flow finishes successfully, I am logged in and able to access the secured resources too of course.

Note: **this is working because I am using an old(ish) Keycloak version**, since v 20 they don't allow access to the UserInfo endpoint if the `openid` scope is not present:

https://github.com/keycloak/keycloak/issues/14184

But anyway, **it still evidencing that we're allowing this on the Spring Security Client side**. I haven't analyzed this in depth to figure out if it is actually a security vulnerability or even a bad practice.

BTW, I am writing an lesson on this, so it's certainly helpful to know your position towards this and what we can expect of the OAuth2 Client functionality in the future :)

**Comment by sjohnr** [comment]
@cpore thanks for reaching out. However, as mentioned above 

> If you believe there is a Security Vulnerability then this is not the proper channel for it. When you clicked on "New Issue", you are presented with 4 options, one of them being "Report a security vulnerability". Please use this channel going forward.

discussing security issues with currently supported versions of the framework in the open is not appropriate. Please see the [Security Policy](https://github.com/spring-projects/spring-security/security/policy) which is also clearly linked from the main page of this project.

> If you try out this configuration, you'll see that we can Log in with this setup (instructions on the README file), and that is done via the UserInfo endpoint.

> 1- the `OAuth2LoginAuthenticationProvider.authenticate` is invoked. This comes into play when the `openid` scope is **not** provided, as you can see here:

The functionality you're describing (when `openid` scope is not present) is the "Login with GitHub" scenario described in the overview of [OAuth 2.0 Login](https://docs.spring.io/spring-security/reference/servlet/oauth2/login/index.html) in the reference. GitHub is an example of a provider that does not implement OpenID Connect 1.0.

If you believe you have found a vulnerability and can provide details, please either report this [directly to GitHub](https://support.github.com/contact/bug-report) (or whatever provider you are using) or if the issue is with OAuth2 Client in Spring Security, by following our [Security Policy](https://github.com/spring-projects/spring-security/security/policy).

> I haven't analyzed this in depth to figure out if it is actually a security vulnerability or even a bad practice

As mentioned above, please do not disclose such findings here. Report them responsibly by following the above linked security policy. I'm going to lock this discussion as it does not seem productive to allow responses that would continue this discussion in public.
